version: '3.8'

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .backend.env
    ports:
      - "8090:8000"

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_REVIEW_LINK=https://g.page/r/CVA1IUylv2nFEBM/review
        - VITE_API_URL=http://localhost:8090
    ports:
      - "8091:80"
    depends_on:
      - backend